"""add column expiry_date

Revision ID: 16c02d4af3f5
Revises: 61924c7159a2
Create Date: 2024-04-03 14:13:06.893928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c02d4af3f5'
down_revision = '61924c7159a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'expiry_date')
    # ### end Alembic commands ###
