"""remove column

Revision ID: 61924c7159a2
Revises: 50d93fd65925
Create Date: 2024-04-03 13:03:00.700634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61924c7159a2'
down_revision = '50d93fd65925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('is_super_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_super_admin')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
