"""add field user

Revision ID: 7c9b4de4903a
Revises: 16c02d4af3f5
Create Date: 2024-04-04 12:36:05.384843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9b4de4903a'
down_revision = '16c02d4af3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('gender', sa.String(length=15), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('user', 'gender')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
