"""add bank detail table

Revision ID: e814254540a4
Revises: e79997c2a245
Create Date: 2024-04-04 19:01:24.689314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e814254540a4'
down_revision = 'e79997c2a245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankdetail',
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_no', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('IFSC_code', sa.String(), nullable=True),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankdetail')
    # ### end Alembic commands ###
