"""remove column

Revision ID: f317c4b33726
Revises: 8d04f570e334
Create Date: 2024-04-03 12:57:32.402973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f317c4b33726'
down_revision = '8d04f570e334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'english_proficiency')
    op.drop_column('user', 'last_education')
    op.drop_column('user', 'city')
    op.drop_column('user', 'document_id')
    op.drop_column('user', 'skill')
    op.drop_column('user', 'addr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('addr', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('skill', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('city', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_education', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('english_proficiency', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('state', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
